#Plots gridded Hestia emission grids at different grid spacing, generated by Daniel Mendoza
#3/14/2016 by John C. Lin (John.Lin@utah.edu)

require("ncdf4");require("fields")
require("maps")
###############
YEAR<-2015
DXs<-c("002deg","01deg","02deg","05deg","1deg","33km")[2]
Sectors<-c("TOTAL","RES","COM","COMPOINT","ELEC","IND","ONROAD","RAILROAD","AIRPORT")
#HestiaDIR<-"/uufs/chpc.utah.edu/common/home/lin-group4/SimCity/DATA/PROCESSED_DATA/UPDATED_HESTIA/"
HestiaDIR<-"/uufs/chpc.utah.edu/common/home/lin-group6/SimCity/DATA/PROCESSED_DATA/UPDATED_HESTIA/"
###############

HestiaDIR<-paste(HestiaDIR,"/","HESTIA_",YEAR,"/",sep="")

#!!!! construct times vector manually, because not every netCDF file has this time stamp
#times<-UTC time  Size:8760
#        POSIX time  Size:8760
#            units: POSIX (base: Jan 1, 1970)
#            long_name: POSIX time

for(i in 1:length(DXs)){
for(j in 1:length(Sectors)){
  tt<-8760/2
  #DX<-"1deg";Sector<-"Com"
  DX<-DXs[i];Sector<-toupper(Sectors[j])
  filenm<-paste(YEAR,"_","0_",DX,"_CO2_",Sector,".nc",sep="")
  if(!file.exists(paste(HestiaDIR,filenm,sep=""))){print(paste(filenm,"not found"));next}
  print(paste("Reading in...",filenm))
  xnc<-nc_open(filename=paste(HestiaDIR,filenm,sep=""),verbose=FALSE)
  #print(xnc)
  lon<-ncvar_get(xnc,varid="x-coord")
  lat<-ncvar_get(xnc,varid="y-coord")
  #time<-ncvar_get(xnc,varid="UTC time")
  #dat.all<-ncvar_get(xnc,varid="C Emissions")
  #dat.all<-ncvar_get(xnc,varid="Carbon Dioxide Emissions")
  dat.all<-ncvar_get(xnc)
  #tt<-floor(length(time)/2)
  dat<-dat.all[tt,,]

  if(sum(!is.na(dat))>0){
    dat[dat==0]<-NA
    X11();par(cex.axis=1.3,cex.main=1.3,cex=1.1)
    image.plot(x=lon,y=lat,z=dat,main=filenm,sub=paste("time=",tt))
  }else{ 
    print("All NAs!  NO PLOT")
  } #if(sum(!is.na(dat))>0){
  nc_close(xnc)
  gc()
} #for(j in 1:length(Sectors)){
} #for(i in 1:length(DXs)){






