#Output observation file as CSV text file
#July 18th, 2017 by John C. Lin (John.Lin@utah.edu)

#######################
YEARs<-c(2015,2016,2017)
#######################

for(i in 1:length(YEARs)){
  YEAR<-YEARs[i]
  datname<-paste0("SimCity_DOE_merge_CO2_allsites_hrly_",YEAR,".rds",sep="")   #generated by "merge_SimCity_DOE_historicCO2V1.r"
  print(paste("Reading in: ",datname))
  dat<-readRDS(datname)

  resultname<-gsub(pattern=".rds",replacement=".csv",datname)
  write.csv(dat,file=resultname)
  print(paste("Writing out:",resultname))
  
} #for(i in 1:length(YEARs)){



